version: "3.9"

services:
  rmqnamesrv:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - "D:/docker-volumes/rocketmq-${ROCKETMQ_VERSION}/namesrv/logs/:/home/rocketmq/logs"
      - "D:/docker-volumes/rocketmq-${ROCKETMQ_VERSION}/namesrv/store/:/home/rocketmq/store"
    command: [ "sh", "mqnamesrv" ]

  rmqbroker:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - "./broker/broker.conf:/home/rocketmq/conf/broker.conf"
      - "D:/docker-volumes/rocketmq-${ROCKETMQ_VERSION}/broker/logs/:/home/rocketmq/logs"
      - "D:/docker-volumes/rocketmq-${ROCKETMQ_VERSION}/broker/store/:/home/rocketmq/store"
    command: [ "sh", "mqbroker", "-c", "/home/rocketmq/conf/broker.conf", "-n", "rmqnamesrv:9876"]
    depends_on:
      - rmqnamesrv

  rmqconsole:
    # SEE https://github.com/apache/rocketmq-dashboard
    # image: styletang/rocketmq-console-ng:1.0.0
    image: apacherocketmq/rocketmq-console:2.0.0
    container_name: rmqconsole
    ports:
      - 58080:8080
    volumes:
      - "D:/docker-volumes/rocketmq-${ROCKETMQ_VERSION}/console/:/tmp/rocketmq-console"
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
      # 默认时区`UTC`，导致日志的输出时间不对。rocketmq-console image基于`Debian GNU/Linux 8 `可以直接通过环境变量`TZ`修改时区
      TZ: Asia/Chongqing
    depends_on:
      - rmqnamesrv
